import requests  # for web requests
from bs4 import BeautifulSoup  # for web scrapping
import smtplib  # send the mail
# email body
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import datetime

now = datetime.datetime.now()
# email content placeholder
message = ''


# url => 'https://news.ycombinator.com/'

# extracting HackerNews Stories
def extract_stories(url):
    print('Extracting HackerNews Stories')
    cnt = ' '
    cnt += '<b>HackerNews Top Stories:</b>\n' + '<br>' + '-' * 50 + '<br>'
    # HackerNews Top Stories :(in bold)
    # ------ 50 times ----------
    response = requests.get(url)
    content = response.content
    soup = BeautifulSoup(content, 'html.parser')
    for i, tag in enumerate(soup.find_all('td', attrs={'class': 'title', 'valign': ''})):
        cnt += ((str(i + 1)) + '. ' + tag.text + "\n" + '<br>' if tag.text != 'More' else ' ')
    return cnt


news_list = extract_stories('https://news.ycombinator.com/')
message += news_list
message += '<br>-------<br>'
message += '<br><br>End of the Message<br><br>'
message += '<em>This is an autogenerated mail.Please Do Not Reply</em>'

# send the email now
print("Composing the mail")
# update the email details (required for authentication)
SERVER = 'smtp.gmail.com'  # "your smtp server"
PORT = 587  # port number
FROM = 'from email address'  # provide the email address of the sender
TO = 'to email address'  # enter email address of the receiver (can be a list)
PASS = 'xxxxxxxxxxxxxxxx'  # 16 digit key generated from google security

msg = MIMEMultipart()

msg['Subject'] = 'Top News Stories on HackerNews [Automated Email] ' + str(now.date())
msg['From'] = FROM
msg['To'] = TO

msg.attach(MIMEText(message, 'html'))

print("Initiating the server")

server = smtplib.SMTP(SERVER, PORT)
# server = smtplib.SMTP SSL('smtp.gmail.com' , 465)
server.set_debuglevel(1)
server.ehlo()
server.starttls()
server.login(FROM, PASS)
server.sendmail(FROM, TO, msg.as_string())
print("Email Sent")

server.quit()
